version: '2'
services:
    lifestudiesapp-app:
        image: lifestudiesapp
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://lifestudiesapp-postgresql:5432/lifestudiesApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    lifestudiesapp-postgresql:
        extends:
            file: postgresql.yml
            service: lifestudiesapp-postgresql
